apiVersion: apps/v1
kind: Deployment
metadata:
  name: gestnet-deployment
  labels:
    app: gestnet
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gestnet
  template:
    metadata:
      labels:
        app: gestnet
    spec:
      containers:
        - name: gestnet
          image: gestnet:1.0
          ports:
            -containerPort: 3000
